{
 "title": "FortiGate Prom Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "fgt_cpu_usage{}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "fgt_memory_usage{}" }
   ]
  },
  {
   "title": "IPv4 Route Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_ipv4_routes{}" }
   ]
  },
  {
   "title": "IPv6 Route Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_ipv6_routes{}" }
   ]
  },
  {
   "title": "Interface Transmit Errors/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fgt_interface_tx_errors_sum{}[1m]) / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "Interface Receive Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fgt_interface_rx_errors_sum{}[1m]) / 1024 / 1024)"
    }
   ]
  },
  {
   "title": "SSLVPN Tunnels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_sslvpn_current_tunnels{}" }
   ]
  },
  {
   "title": "SSL VPN Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fgt_sslvpn_current_connections{}"
    }
   ]
  },
  {
   "title": "SSLVPN Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_sslvpn_current_users{}" }
   ]
  },
  {
   "title": "SSL VPN Total Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_sslvpn_max_connections{}" }
   ]
  },
  {
   "title": "IPSec Outbound MB/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(fgt_ipsec_vpn_outbound_bytes{}[1m]) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "IPSec Inbound MB/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "rate(fgt_ipsec_vpn_inbound_bytes{}[1m]) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "IPSec VPN Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_ipsec_vpn_connections" }
   ]
  },
  {
   "title": "IPSec Tunnels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fgt_ipsec_vpn_tunnels{}" }
   ]
  },
  {
   "title": "Exporter Saturation Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(fos_metric_polling_interval_saturation_sum{}[1m])"
    }
   ]
  },
  {
   "title": "Conserve Mode Enabled",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "fgt_conserve_mode_info{conserve_mode=\"True\"}"
    }
   ]
  }
 ]
}